[package]
name = "debrief"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = { version = "0.37.0", features = ["rustls-webpki-tokio", "tokio"] }
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.81"
chrono = "0.4.37"
chatgpt_rs = "1.2.3"
log = "0.4.21"
env_logger = "0.11.3"
async-trait = "0.1.80"
reqwest = { version = "0.12.4", features = ["json"] }
serde_json = "1.0.116"
serde = "1.0.200"
url = "2.5.0"